## Table Data

In [1]:
import logging
import pandas as pd

logger = logging.getLogger(__name__)

In [2]:
csv_file = "../../res/dataset/tables/meeting_management/time_slots.txt"
table_data = pd.read_csv(csv_file, sep=",", dtype="string").fillna("-")
table_data

Date  Time_slot       Name    Surname                          Email  \
0   01.04.22  1000-1015    Juergen     Bieber         JurgenBieber@rhyta.com   
1   01.04.22  1015-1030      Ralph  Eberhardt  RalphEberhardt@jourrapide.com   
2   01.04.22  1045-1100     Dennis      Braun        DennisBraun@teleworm.us   
3   01.04.22  1100-1145     Julia      Farber        JuliaFarber@teleworm.us   
4   01.04.22  1200-1215     Sophie      Boehm        SophieBoehm@teleworm.us   
5   04.04.22  0900-0915      Maria    Schmitz       MariaSchmitz@armyspy.com   
6   04.04.22  1330-1400    Steffen    Schulze  SteffenSchulze@jourrapide.com   
7   04.04.22  1415-1430  Katharina      Nacht  KatharinaNacht@jourrapide.com   
8   05.04.22  1600-1615     Robert   Pfeiffer     RobertPfeiffer@armyspy.com   
9   05.04.22  1615-1700      Laura    Freytag         LauraFreytag@rhyta.com   
10  05.04.22  1700-1715    Florian     Wagner       FlorianWagner@dayrep.com   

         Phone                           Private Notes  
0   6138848100                           first meeting  
1   2622449580  wants to know about programming basics  
2   6020797114              interesting project advice  
3   5323961496                                kick off  
4   3940528208                            regular meet  
5   7252323962                   questions about exams  
6   9383460916                                       -  
7   7255610166                            regular meet  
8   9519884353                 questions about project  
9   3417252072                                kick off  
10  6281589915                           first meeting

## Internal Tabular Representation

In [3]:
from src.datamodel.Table import Table

In [4]:
table = Table(table_data, "time_slots", "meeting planning")

### Embedd text aligned table data using: Table Search Using a Deep Contextualized Language Model
https://arxiv.org/pdf/2005.09207.pdf

In [5]:
from src.candidate_reranker.table_embedding.TableEmbedder import TableEmbedder

2022-07-14 20:06:24.296381: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-14 20:06:24.296402: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [6]:
table_embedder = TableEmbedder.initialize(
    "/home/pandavid/uni/BA/tfhub_models/bert_preprocess",
    "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"
)

2022-07-14 20:06:26.047763: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-07-14 20:06:26.047786: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-07-14 20:06:26.047802: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (WorkPad): /proc/driver/nvidia/version does not exist
2022-07-14 20:06:26.047963: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
print(table_embedder.create_feature_from_data(table, "Select name, surname and date."))

{'sequence_output': <tf.Tensor: shape=(1, 128, 768), dtype=float32, numpy=
array([[[ 0.44860032,  0.5289162 , -0.44279695, ..., -0.07975885,
         -0.14798123, -0.14159767],
        [ 0.22649027,  0.20695348, -0.00820719, ..., -0.05873903,
          0.20263632,  0.05287073],
        [-0.5409682 , -0.05221596,  0.07211123, ..., -0.73524797,
          0.5482847 ,  0.12314891],
        ...,
        [ 0.51098526,  0.11550657,  0.11942683, ..., -0.95363474,
          0.21883017, -0.17876464],
        [-0.82673496,  0.49125063,  0.25076252, ..., -0.6760485 ,
         -0.38570833, -0.47418112],
        [-0.27180085, -0.36675453,  0.12596191, ..., -0.23171225,
         -0.0480305 , -0.5355417 ]]], dtype=float32)>, 'pooled_output': <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 0.6177336 , -0.11666167, -0.9978473 ,  0.14973062,  0.89233553,
         0.15162507, -0.65523744, -0.12273952, -0.98505193,  0.5787405 ,
        -0.95946926,  0.9657118 , -0.931834  ,  0.9426598 , -0.78685

In [8]:
print(table_embedder.create_feature_from_column_names(table, "Select name, surname and date"))

{'sequence_output': <tf.Tensor: shape=(1, 128, 768), dtype=float32, numpy=
array([[[ 0.8371103 ,  0.26075476, -0.1578682 , ..., -0.08931629,
         -0.479506  , -0.0602927 ],
        [ 0.11424296,  0.11574483,  0.21506521, ..., -0.32691646,
          0.00436516,  0.12428103],
        [-0.08033124, -0.37099838,  0.33996361, ..., -0.90410566,
          0.55974954, -0.15221451],
        ...,
        [ 0.10710357,  0.1442883 ,  0.15879966, ..., -0.2685287 ,
         -0.30996737,  0.1545791 ],
        [ 0.08872418,  0.16892575,  0.10798704, ..., -0.2540834 ,
         -0.30326   ,  0.14856185],
        [ 0.06725889,  0.1595004 ,  0.08469188, ..., -0.29614002,
         -0.3054224 ,  0.19168165]]], dtype=float32)>, 'pooled_output': <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.35464147, -0.20940515, -0.95593786,  0.50239307,  0.85196054,
        -0.04843258, -0.11062284, -0.0427837 , -0.85450053, -0.70843196,
        -0.8901298 ,  0.9294022 ,  0.09784873,  0.5207928 ,  0.34817